Inițializare populație balene X_i (i = 1, 2, ..., n)
Calcul fitness pentru fiecare agent_de_căutare
X_best = cel mai bun agent de agent_de_căutare 
cât timp (t < număr_maxim_iterații):
{
    pentru agent_de_căutare, listă_agenți_căutare:
    {
        Actualizează a, A, C, l, p 
        dacă (p < 0.5):
        {
            dacă (|A| < 1):
            {
                Actualizează poziția agent_de_căutare_curent dupa eq încercuire
            }
            altfel:
            {   
                Selectează agent_de_căutare_random (X_rand)
                Actualizează poziția agent_de_căutare_curent dupa agent_de_căutare_random
            }
        }
        altfel:
        {
            Actualizează poziția agent_de_căutare_curent dupa eq spiralare
        }     
    }
    Verificare dacă agent_de_căutare iese din spațiul de căutare și corectare
    Calcul fitness pentru fiecare agent_de_căutare
    Actualizează X_best dacă există o soluție mai bună
    t = t + 1
}
returnează X_best
    
    
