consum = consum total pentru toate nodurile
productie = producție totală pentru toate nodurile
stare_grid = consum - productie
baterii = stare curentă baterii
profil_referinta = 0
dacă (stare_grid >= 0):
{
    dacă (preț_curent_energie >= preț_mediu_energie):
    {
        dacă (baterii >= cantitatea minimă necesară energie baterii):
        {
            max_descarcare = baterii - cantitatea minimă necesară energie baterii
            profil_referinta = max(minim_retea, stare_grid - max_descarcare)
        }
        altfel: 
        {
            profil_referinta = stare_grid
        }
    }
    altfel:
    {
        profil_referinta = stare_grid
    }
}
altfel: 
{
    dacă (baterii < cantitatea maximă energie baterii):
    {
        necesar_incarcare = cantitatea maximă energie baterii - baterii 
        max_incarcare = min(|stare_grid|, necesar_incarcare)
        profil_referinta = stare_grid + max_incarcare
    }
    altfel 
    {
        profil_referinta = -max(|stare_grid|, |minim_retea|)
    }
}
